### ISSUE TITLE
Add capability for specifying arguments to command

### ISSUE THREAD

**Issue by avanhatt** [cucapra/turnt#1]

**Comment by sampsyo** [comment]
Inspired by Lit, a cool way to do this would be to parse comments embedded in text files. These comments could specify either the entire command (overriding the configured command) or just arguments to append onto the end of the command. Something like this:

```
// CMD: clang -c {filename}
```

Or:

```
// ARGS: 1 2 'foo'
```

**Comment by sampsyo** [comment]
Added `CMD:` in 429299c2f2b1cdc95d979c2a450a60b92debf21c.
