### ISSUE TITLE
turnt runs default from a bin/sh shell, but doesn't work on ubuntu unless you specify to run from a bin/bash shell

### ISSUE THREAD

**Issue by thomasyang18** [cucapra/turnt#14]
I'm very new to Linux, so forgive me if this is a newbie mistake, but when I ran turnt, the bin/sh shell wasn't recognizing the brili command. I had to go find the turnt.py file and in the subprocess.run() command, specify the shell that I was using (bin/bash), and then it worked.

Not sure if there's an option on python to dynamically select the shell to execute, probably not worth the hassle to implement anyways. Just a heads up to any future students who want to use this online resource.

**Comment by sampsyo** [comment]
Interesting! I suppose the likely culprit is that you have your `$PATH` set up to include the `brili` executable in your `.bashrc`, but not your generic `.profile` or other similar file that would also be read by the plain Bourne shell?

It is possible to specify a specific shell to use for subcommands using [the `executable` parameter to `Popen`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen). But maybe the appropriate thing would just be to document the fact that this uses `sh` so you'll want to either set variables in a way that works for that or use `bash -c '...'` as your command?

**Comment by thomasyang18** [comment]
My .profile and .bashrc both have

export PATH="$PATH:~/.yarn/bin"
export PATH="$PATH:~/.local/bin"

which was why I was so confused, since everywhere online it said that sh reads from .profile. But then apparently sh can read from etc/profile, but etc/profile is readonly, so I tried sudo chmod +w, but sudo chmod +w isn't working and -

Point is, long rabbit confusing rabbithole. Then I found out you can just edit the turnt.py file, so I thought that was the solution.

Then you brought up the point that you can just do bash -c '...', and that works fine for me now. Newbie issues, my bad :)

Sorry for the issue. If I'm having problems with the online course in the future, where should I send my inquiries?

**Comment by sampsyo** [comment]
No problem at all! Thanks for elaborating.

Discussion threads on [the cs6120 repo](https://github.com/sampsyo/cs6120) would be a good place for those general questions.
