### ISSUE TITLE
turnt should check standard error on running commands

### ISSUE THREAD

**Issue by avanhatt** [cucapra/turnt#2]
If I create a command in turnt.toml that fails, turnt succeeds and write an empty file:

```
tests (master) $ turnt --save merge-sort.c 
1..1
ok 1 - merge-sort.c
tests (master) $ make merge-sort.c_partitioned.out
make: *** No rule to make target `merge-sort.c_partitioned.out'.  Stop.
```

**Comment by sampsyo** [comment]
It should probably do two things:
- Check for nonzero exit codes!
- When a command fails, print its standard error to Turnt's standard error. (It's currently just captured and suppressed.)
