### ISSUE TITLE
Turnt can't handle stderr redirection

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/turnt#25]
I am testing a command that puts its interesting output into stderr. I'd like to direct stderr to stdout, then let turnt funnel that out to filename.out. Sadly something like `2>&1` does not work.

As a workaround, I'm currently doing `my_command ... {filename} ... 2>temp.txt; cat temp.txt`.

FWIW, [these folks](https://linuxize.com/post/bash-redirect-stderr-stdout/#redirecting-stderr-to-stdout) suggest that order is rather important. Maybe that's what is tripping us up?

cc: https://github.com/cucapra/pollen/pull/29#discussion_r1158951734

**Comment by sampsyo** [comment]
Hmm; I was attempting to dive into this in an isolated setup and I couldn't seem to reproduce the problem. I made the `turnt.toml`:

```toml
command = "ls does_not_exist 2>&1"
```

That is, Turnt is configured to run a command that prints an error to stderr and redirects that to stdout. Then you just need a meaningless test file like `x.t`:

```
RETURN: 1
```

…just to specify that the `ls` command is expected to have status code 1. If I then do `turnt --save x.t`, the saved output `x.out` now contains:

```
ls: does_not_exist: No such file or directory
```

…which is exactly what we want.

There is a chance we have misdiagnosed the problem. If you get a chance to try this isolated test case on your machine, can you post the results? It could depend on the specific shell or something, which would be annoying. But if you get the same results as me, then perhaps it is not Turnt's fault, and we should return to looking directly at the Pollen case.

**Comment by anshumanmohan** [comment]
Thanks for looking at this! On running it as you have it set up, I get: 
```
1..1
not ok 1 - x.t
# exit code: 2, expected: 1
```
and no `x.out` is created.

On changing `x.t` to:
```
RETURN: 2
```
I do get an `x.out` that contains
```
ls: cannot access 'does_not-exist': No such file or directory
```

**Comment by anshumanmohan** [comment]
I'll tinker with the original offending Pollen invocation some more!

**Comment by anshumanmohan** [comment]
Confirmed that the issue was on my end; see the PR above if you're curious. Thanks for looking at this, and sorry for the bother!

**Comment by sampsyo** [comment]
Great news!
